ktor:
    application:
        modules:
            - com.musicstore.ApplicationKt.module
    deployment:
        port: 8080
storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://localhost:5432/musicstore"
  user: "postgres"
  password: "senha"
jwt:
  secret: "secret"
  issuer: "http://localhost:8080/"
  audience: "http://localhost:8080/hello"
  realm: "ktor sample app"
